### ISSUE TITLE
Error: 'Trainer' has no attribute 'add_argparse_args'

### ISSUE THREAD

**Issue by ArmanAvesta** [UARK-AICV/3DConvCaps#2]
Hi!

I am trying to run train.py, but I receive this error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-4975a8771385>", line 41, in <module>
    parser = Trainer.add_argparse_args(parser)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

Apparently, the pytorch lightning's Trainer does not have the method add_argparse_args in this line:

    parser = Trainer.add_argparse_args(parser)

Would you please help and tell me how I can get around this error? Thank you so much :) 

Best,
Arman

**Comment by ArmanAvesta** [comment]
I installed a previous version of pytorch-lightning (version 1.8.6) and this error went away :)
